version: "3.6"

services:
 sut:
  build:
   context: ./test
   args:
    ENGINE_VERSION: ${ENGINE_VERSION:-5.7.0}
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/mail/"
    - "world_data:/root/.minetest/worlds/world"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
  ports:
    - "30000:30000/udp"

volumes:
  world_data: {}